name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"   
  workflow_dispatch:          
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.5.0
        with:
          github_user_name: syfar2004
          github_token: ${{ github.token }}
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push snake SVG to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: "chore: update snake animation [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}